import { jsPDF } from "jspdf";
import type { Approval, Payment } from "./store";

function brandHeader(doc: jsPDF, title: string) {
  doc.setFillColor(124, 58, 237); // primary violet
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AETHER", 14, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Campus Operating System", 14, 23);
  doc.setFontSize(11);
  doc.text(title, 196, 17, { align: "right" });
  doc.setTextColor(20, 20, 20);
}

function brandFooter(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by AETHER · ${new Date().toLocaleString()} · This is a system-generated document.`,
    105,
    287,
    { align: "center" },
  );
}

export function downloadApprovalPdf(a: Approval) {
  const doc = new jsPDF();
  brandHeader(doc, a.kind.toUpperCase());

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(a.title, 14, 45);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  doc.text(`Reference ID: AET-${a.id.toUpperCase()}`, 14, 52);
  doc.text(`Status: ${a.status}`, 14, 58);
  doc.text(`Requester: ${a.by}`, 14, 64);
  doc.text(`Issued: ${new Date().toLocaleDateString()}`, 14, 70);

  // details
  if (a.details && Object.keys(a.details).length) {
    doc.setTextColor(20, 20, 20);
    doc.setFont("helvetica", "bold");
    doc.text("Details", 14, 84);
    doc.setFont("helvetica", "normal");
    let y = 92;
    Object.entries(a.details).forEach(([k, v]) => {
      doc.text(`${k.charAt(0).toUpperCase() + k.slice(1)}: ${v}`, 14, y);
      y += 6;
    });
  }

  // chain
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 20);
  doc.text("Approval Chain", 14, 130);
  doc.setFont("helvetica", "normal");
  let y = 138;
  a.chain.forEach((s, i) => {
    const mark = s.status === "done" ? "✓" : s.status === "rejected" ? "✗" : "•";
    doc.text(`${mark} ${i + 1}. ${s.label} (${s.by})`, 14, y);
    if (s.at) {
      doc.setTextColor(120, 120, 120);
      doc.text(s.at, 130, y);
      doc.setTextColor(20, 20, 20);
    }
    y += 7;
  });

  // signature
  doc.setDrawColor(180, 180, 180);
  doc.line(140, 240, 195, 240);
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text("Authorized Signature", 167, 247, { align: "center" });

  brandFooter(doc);
  doc.save(`aether-${a.kind.toLowerCase().replace(/\s+/g, "-")}-${a.id}.pdf`);
}

export function downloadReceiptPdf(p: Payment) {
  const doc = new jsPDF();
  brandHeader(doc, "PAYMENT RECEIPT");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Receipt", 14, 45);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  doc.text(`Transaction: ${p.txn}`, 14, 52);
  doc.text(`Method: ${p.method}`, 14, 58);
  doc.text(`Date: ${new Date(p.at).toLocaleString()}`, 14, 64);

  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.text("Items", 14, 80);
  doc.setFont("helvetica", "normal");
  let y = 88;
  p.items.forEach((it) => {
    doc.text(it.label, 14, y);
    doc.text(`Rs. ${it.amount}`, 196, y, { align: "right" });
    y += 7;
  });
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, 196, y);
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text("Total", 14, y);
  doc.text(`Rs. ${p.amount}`, 196, y, { align: "right" });

  brandFooter(doc);
  doc.save(`aether-receipt-${p.txn}.pdf`);
}
